### ISSUE TITLE
adding new containers

### ISSUE THREAD

**Issue by nabil215** [katharostech/docker_lizardfs#1]
how can i add new container for example a new container of a new chunkserver and visualise replication of file between chunks 
it's urgent and in need help
thank you

**Comment by zicklag** [comment]
Hey there, you should be able to `docker-compose scale chunkserver=[number]` if you are using Docker compose for the deployment. Then you can view the replication through the Web UI.

Are you using Docker compose or Docker swarm?

**Comment by nabil215** [comment]
hello zicklag!
what i did is that i ran `docker-compose up -d`  and a list of container is created (master 2 client but one chunkserver ) should i stop those container and  execute  your command 
and im not using Docker swarm

**Comment by zicklag** [comment]
You shouldn't have to stop anything. Just run the scale command it it will add/remove containers to get the scale of that particular service to the number that you specified. To be clear, the number provided when you do `chunkserver=[numer]` is the number of containers that you want *total*, not however many to add.

**Comment by AbdelghaniKabli** [comment]
hey zicklag 
im working too on dockerLizardfs wherever i do your command it does not create a new one maybe i'm wrong in it ,it show me 

> couldn't connect to docker daemon at http+docker ://locakunisocket is it running

> its` a no standar location specifiy the URL with the docker Host environnement variable

can u show me the exact command

**Comment by zicklag** [comment]
Hello @AbdelghaniKabli, I just tested it out and I get that error too, if I don't run `docker-compose` with sudo. An alternative to sudo would be to add the user account you are using to the `docker` group.

Try running:
```
sudo docker-compose up -d
```

And to scale to 5 chunkservers if you have already started the cluster:
```
sudo docker-compose scale chunkserver=5
```

That error is unfortunately very confusing; I found the solution by searching the Docker Compose bugs on GitHub.

**Comment by AbdelghaniKabli** [comment]
yeah its was because of sudo .
and now i would like to replicate a text file i created 
but it seems thas the goal(number of replication) is set to 1 and i would like to change it .
any help??

**Comment by zicklag** [comment]
First you need to exec into one of the client containers:

    $ sudo docker-compose exec client1 bash

Then you need to switch directory to the LizardFS mount:

    $ cd /mnt/mfs

Now you can see the LizardFS replication goals for the files in the mount:

    $ lizardfs getgoal *
    myfile.txt: 1

To change the goal just run:

    $ lizardfs setgoal 3 myfile.txt
    myfile.txt: 3

You can find more information setting the goal in the [LizardFS documentation](https://docs.lizardfs.com/adminguide/replication.html?highlight=goal#set-and-show-the-goal-of-a-file-directory).

**Comment by AbdelghaniKabli** [comment]
thanks it works now i want to stop one chunkserver to see if the files still exist in the other
and is there a solution to set default goals for each file you create whithout having to set it to each one

**Comment by zicklag** [comment]
You can see all of the servers that are running:

    $ sudo docker-compose ps

Then you can scale the chunkservers back down to remove one:

    $ sudo docker-compose scale chunkserver=2 # if you had three chunkservers

After that you should still be able to see the file in the client container.

**Comment by AbdelghaniKabli** [comment]
but i like to delete the first chunkserver where i first created my files

**Comment by zicklag** [comment]
Ah, in that case you can use the Docker CLI:

    $ docker rm -f dockerlizardfs_chunkserver_1

Note that the `dockerlizardfs` prefix comes from the directory that the docker-compose file was in. If you are in a directory with a different name that will be different. `docker-compose ps` will show you the exact name.

**Comment by AbdelghaniKabli** [comment]
so now i should find my files in the other chunkservers??
and what about to set default replication number(default goal for each file created)

and thanks a lot man!

**Comment by zicklag** [comment]
You can't get to your file from the chunkservers because the chunkservers don't mount the filesystem, but you should be able to see the replicas on those other chunkservers in the Web UI.

You *should* be able to get to the file in the `client1` or `client2` containers where the filesystem is mounted: `/mnt/mfs`.

If you want to set the default replication, you can just run `lizardfs setgoal 3 .` in the `/mnt/mfs` dir in one of the client containers. That will set the goal on the root dir and all files in a directory inherit the goal of the directory they are in by default.

> and thanks a lot man!

No problem.  It's cool to see that this is useful to people! :slightly_smiling_face:
